const rebootActionTypes = {
  SUBMIT_REBOOT_START: 'SUBMIT_REBOOT_START',
  SUBMIT_REBOOT_SUCCESS: 'SUBMIT_REBOOT_SUCCESS',
  SUBMIT_REBOOT_FAILURE: 'SUBMIT_REBOOT_FAILURE',
};

export default rebootActionTypes;