const deviceCommandHistoryActionTypes = {
  FETCH_DEVICE_COMMAND_HISTORIES_START: 'FETCH_DEVICE_COMMAND_HISTORIES_START',
  FETCH_DEVICE_COMMAND_HISTORIES_SUCCESS: 'FETCH_DEVICE_COMMAND_HISTORIES_SUCCESS',
  FETCH_DEVICE_COMMAND_HISTORIES_FAILURE: 'FETCH_DEVICE_COMMAND_HISTORIES_FAILURE',
};

export default deviceCommandHistoryActionTypes;