const deviceCommandHistoryActionTypes = {
  // Index
  FETCH_DEVICE_COMMAND_HISTORIES_START: 'FETCH_DEVICE_COMMAND_HISTORIES_START',
  FETCH_DEVICE_COMMAND_HISTORIES_SUCCESS: 'FETCH_DEVICE_COMMAND_HISTORIES_SUCCESS',
  FETCH_DEVICE_COMMAND_HISTORIES_FAILURE: 'FETCH_DEVICE_COMMAND_HISTORIES_FAILURE',
  SET_FETCH_DEVICE_COMMAND_HISTORIES_LAZY_PARAMS: 'SET_FETCH_DEVICE_COMMAND_HISTORIES_LAZY_PARAMS',
  RESET_FETCH_DEVICE_COMMAND_HISTORIES_LAZY_PARAMS: 'RESET_FETCH_DEVICE_COMMAND_HISTORIES_LAZY_PARAMS',
};

export default deviceCommandHistoryActionTypes;