/*
 * Copyright (C) 2021 Intel Corporation
 * SPDX-License-Identifier: MIT
 */

const deviceCommandActionTypes = {
  // Fetch dropdown options
  FETCH_DEVICE_COMMAND_OPTIONS_START: 'FETCH_DEVICE_COMMAND_OPTIONS_START',
  FETCH_DEVICE_COMMAND_OPTIONS_SUCCESS: 'FETCH_DEVICE_COMMAND_OPTIONS_SUCCESS',
  FETCH_DEVICE_COMMAND_OPTIONS_FAILURE: 'FETCH_DEVICE_COMMAND_OPTIONS_FAILURE',
};

export default deviceCommandActionTypes;