const deviceCommandActionTypes = {
  FETCH_DEVICE_COMMANDS_START: 'FETCH_DEVICE_COMMANDS_START',
  FETCH_DEVICE_COMMANDS_SUCCESS: 'FETCH_DEVICE_COMMANDS_SUCCESS',
  FETCH_DEVICE_COMMANDS_FAILURE: 'FETCH_DEVICE_COMMANDS_FAILURE',
};

export default deviceCommandActionTypes;