image: registry.gitlab.com/desmondsow/i-iot-portal:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: inteliotportal
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  #  - test
  - deploy

#unit_test:
#  stage: test
#  script:
#    - cp .env.staging .env
#    - composer install
#    - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
#    - apt install -y nodejs
#    - npm ci
#    - npm rebuild node-sass
#    - npm run production
#    - php artisan key:generate
#    - php artisan config:cache
#    - php artisan route:cache
#    - php artisan optimize
#    - php artisan migrate
#    - vendor/bin/phpunit

deploy_staging:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA" --stagingSshHost=root@"$STAGING_SSH_HOST" --projectRepository="$PROJECT_REPOSITORY" --serverName="$SERVER_NAME" --appHost="$APP_HOST" --dbPassword="$DB_PASSWORD" --mqttExternalEndpoint="$MQTT_EXTERNAL_ENDPOINT" --unblockIp="$UNBLOCK_IP" --serverIp="$STAGING_SSH_HOST"
  environment:
    name: production
    url: $APP_URL
  when: manual
  only:
    - master