version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: dockerfiles/Dockerfile.staging.app
        image: inteliotportal
        container_name: inteliotportal-app
        restart: unless-stopped
        volumes:
            - ./storage:/var/www/storage
        depends_on:
            - db
        networks:
            - inteliotportal

    db:
        image: mysql:latest
        container_name: inteliotportal-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - 3306:3306
        networks:
            - inteliotportal

    nginx:
        build:
            context: ./
            dockerfile: dockerfiles/Dockerfile.staging.nginx
        container_name: inteliotportal-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./storage/logs/:/var/log/nginx
        networks:
            - inteliotportal

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: inteliotportal-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${PMA_PORT}:80'
        depends_on:
            - '${PMA_DB_ENGINE}'
        networks:
            - inteliotportal

networks:
    inteliotportal:
        driver: bridge