FROM vernemq/vernemq:latest-alpine

ENV LOCAL_UID=65534
ENV LOCAL_GID=65534

USER root

COPY --from=inteliotportal-build /certs/localhost.crt /usr/local/share/ca-certificates/localhost.crt

RUN chmod 644 /usr/local/share/ca-certificates/localhost.crt && update-ca-certificates

USER $LOCAL_UID:$LOCAL_GID


