const decommissionActionTypes = {
  // Submit Decommission
  SUBMIT_DECOMMISSION_START: 'SUBMIT_DECOMMISSION_START',
  SUBMIT_DECOMMISSION_SUCCESS: 'SUBMIT_DECOMMISSION_SUCCESS',
  SUBMIT_DECOMMISSION_FAILURE: 'SUBMIT_DECOMMISSION_FAILURE',
};

export default decommissionActionTypes;