const deviceStatusActionTypes = {
  FETCH_DEVICE_STATUSES_START: 'FETCH_DEVICE_STATUSES_START',
  FETCH_DEVICE_STATUSES_SUCCESS: 'FETCH_DEVICE_STATUSES_SUCCESS',
  FETCH_DEVICE_STATUSES_FAILURE: 'FETCH_DEVICE_STATUSES_FAILURE',
};

export default deviceStatusActionTypes;