const deviceStatusActionTypes = {
  // Fetch dropdown options
  FETCH_DEVICE_STATUS_OPTIONS_START: 'FETCH_DEVICE_STATUS_OPTIONS_START',
  FETCH_DEVICE_STATUS_OPTIONS_SUCCESS: 'FETCH_DEVICE_STATUS_OPTIONS_SUCCESS',
  FETCH_DEVICE_STATUS_OPTIONS_FAILURE: 'FETCH_DEVICE_STATUS_OPTIONS_FAILURE',
};

export default deviceStatusActionTypes;