const aotaActionTypes = {
  // Submit AOTA
  SUBMIT_AOTA_START: 'SUBMIT_AOTA_START',
  SUBMIT_AOTA_SUCCESS: 'SUBMIT_AOTA_SUCCESS',
  SUBMIT_AOTA_FAILURE: 'SUBMIT_AOTA_FAILURE',
};

export default aotaActionTypes;