const apiTokenActionTypes = {
  // Read
  FETCH_API_TOKENS_START: 'FETCH_API_TOKENS_START',
  FETCH_API_TOKENS_SUCCESS: 'FETCH_API_TOKENS_SUCCESS',
  FETCH_API_TOKENS_FAILURE: 'FETCH_API_TOKENS_FAILURE',
};

export default apiTokenActionTypes;