const deviceActionTypes = {
  FETCH_DEVICE_START: 'FETCH_DEVICE_START',
  FETCH_DEVICE_SUCCESS: 'FETCH_DEVICE_SUCCESS',
  FETCH_DEVICE_FAILURE: 'FETCH_DEVICE_FAILURE',
  UPDATE_DEVICE_START: 'UPDATE_DEVICE_START',
  UPDATE_DEVICE_SUCCESS: 'UPDATE_DEVICE_SUCCESS',
  UPDATE_DEVICE_FAILURE: 'UPDATE_DEVICE_FAILURE',
  FETCH_DEVICES_START: 'FETCH_DEVICES_START',
  FETCH_DEVICES_SUCCESS: 'FETCH_DEVICES_SUCCESS',
  FETCH_DEVICES_FAILURE: 'FETCH_DEVICES_FAILURE',
};

export default deviceActionTypes;