const cotaActionTypes = {
  // Submit COTA
  SUBMIT_COTA_START: 'SUBMIT_COTA_START',
  SUBMIT_COTA_SUCCESS: 'SUBMIT_COTA_SUCCESS',
  SUBMIT_COTA_FAILURE: 'SUBMIT_COTA_FAILURE',
};

export default cotaActionTypes;