apiVersion: v1
kind: Service
metadata:
  name: {{ include "vernemq.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    helm.sh/chart: {{ include "vernemq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: empd
    port: 4369
  - name: metrics
    port: 8888
    targetPort: prometheus
  selector:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
