{{- if .Values.rbac.create -}}
{{/* VerneMQ needs to query k8s apiserver to list the other pods in the namespace */}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vernemq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    helm.sh/chart: {{ include "vernemq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vernemq.serviceAccountName" . }} {{/* Name is case sensitive */}}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role {{/* this must be Role or ClusterRole */}}
  name: {{ include "vernemq.fullname" . }} {{/* this must match the name of the Role or ClusterRole you wish to bind to */}}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}