apiVersion: v1
kind: Service
metadata:
  name: {{ include "vernemq.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    helm.sh/chart: {{ include "vernemq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.service.labels }}
    {{ toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
{{- else if eq .Values.service.type "LoadBalancer" }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.service.type }}
{{- end }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
{{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{ toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end -}}
{{- end }}
{{- with .Values.service.externalIPs }}
  externalIPs:
    {{ toYaml . | nindent 4 }}
{{- end }}
  ports:
    {{- if .Values.service.mqtt.enabled }}
    - port: {{ .Values.service.mqtt.port }}
      targetPort: mqtt
      name: mqtt
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.mqtt.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.mqtts.enabled }}
    - port: {{ .Values.service.mqtts.port }}
      targetPort: mqtts
      name: mqtts
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.mqtts.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.ws.enabled }}
    - port: {{ .Values.service.ws.port }}
      targetPort: ws
      name: ws
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ws.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.wss.enabled }}
    - port: {{ .Values.service.wss.port }}
      targetPort: wss
      name: wss
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.wss.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
