{{- if and .Values.rbac.create .Values.rbac.serviceAccount.create -}}
{{/* VerneMQ needs to query k8s apiserver to list the other pods in the namespace */}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vernemq.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vernemq.name" . }}
    helm.sh/chart: {{ include "vernemq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}