const commandHistoryActionTypes = {
  FETCH_COMMAND_HISTORY_START: 'FETCH_COMMAND_HISTORY_START',
  FETCH_COMMAND_HISTORY_SUCCESS: 'FETCH_COMMAND_HISTORY_SUCCESS',
  FETCH_COMMAND_HISTORY_FAILURE: 'FETCH_COMMAND_HISTORY_FAILURE',
};

export default commandHistoryActionTypes;