const savedCommandActionTypes = {
  // Index
  FETCH_SAVED_COMMANDS_START: 'FETCH_SAVED_COMMANDS_START',
  FETCH_SAVED_COMMANDS_SUCCESS: 'FETCH_SAVED_COMMANDS_SUCCESS',
  FETCH_SAVED_COMMANDS_FAILURE: 'FETCH_SAVED_COMMANDS_FAILURE',
  SET_FETCH_SAVED_COMMANDS_LAZY_PARAMS: 'SET_FETCH_SAVED_COMMANDS_LAZY_PARAMS',
  RESET_FETCH_SAVED_COMMANDS_LAZY_PARAMS: 'RESET_FETCH_SAVED_COMMANDS_LAZY_PARAMS',

  // Create
  CREATE_SAVED_COMMAND_START: 'CREATE_SAVED_COMMAND_START',
  CREATE_SAVED_COMMAND_SUCCESS: 'CREATE_SAVED_COMMAND_SUCCESS',
  CREATE_SAVED_COMMAND_FAILURE: 'CREATE_SAVED_COMMAND_FAILURE',

  // Read
  FETCH_SAVED_COMMAND_START: 'FETCH_SAVED_COMMAND_START',
  FETCH_SAVED_COMMAND_SUCCESS: 'FETCH_SAVED_COMMAND_SUCCESS',
  FETCH_SAVED_COMMAND_FAILURE: 'FETCH_SAVED_COMMAND_FAILURE',

  // Update
  UPDATE_SAVED_COMMAND_START: 'UPDATE_SAVED_COMMAND_START',
  UPDATE_SAVED_COMMAND_SUCCESS: 'UPDATE_SAVED_COMMAND_SUCCESS',
  UPDATE_SAVED_COMMAND_FAILURE: 'UPDATE_SAVED_COMMAND_FAILURE',

  // Delete Mass
  DELETE_SAVED_COMMANDS_START: 'DELETE_SAVED_COMMANDS_START',
  DELETE_SAVED_COMMANDS_SUCCESS: 'DELETE_SAVED_COMMANDS_SUCCESS',
  DELETE_SAVED_COMMANDS_FAILURE: 'DELETE_SAVED_COMMANDS_FAILURE',

  // Fetch dropdown options
  FETCH_SAVED_COMMAND_OPTIONS_START: 'FETCH_SAVED_COMMAND_OPTIONS_START',
  FETCH_SAVED_COMMAND_OPTIONS_SUCCESS: 'FETCH_SAVED_COMMAND_OPTIONS_SUCCESS',
  FETCH_SAVED_COMMAND_OPTIONS_FAILURE: 'FETCH_SAVED_COMMAND_OPTIONS_FAILURE',
};

export default savedCommandActionTypes;