const savedCommandActionTypes = {
  // Create
  CREATE_SAVED_COMMAND_START: 'CREATE_SAVED_COMMAND_START',
  CREATE_SAVED_COMMAND_SUCCESS: 'CREATE_SAVED_COMMAND_SUCCESS',
  CREATE_SAVED_COMMAND_FAILURE: 'CREATE_SAVED_COMMAND_FAILURE',
};

export default savedCommandActionTypes;