const deviceEventActionTypes = {
  // Fetch dropdown options
  FETCH_DEVICE_EVENT_OPTIONS_START: 'FETCH_DEVICE_EVENT_OPTIONS_START',
  FETCH_DEVICE_EVENT_OPTIONS_SUCCESS: 'FETCH_DEVICE_EVENT_OPTIONS_SUCCESS',
  FETCH_DEVICE_EVENT_OPTIONS_FAILURE: 'FETCH_DEVICE_EVENT_OPTIONS_FAILURE',
};

export default deviceEventActionTypes;