const deviceEventActionTypes = {
  FETCH_DEVICE_EVENTS_START: 'FETCH_DEVICE_EVENTS_START',
  FETCH_DEVICE_EVENTS_SUCCESS: 'FETCH_DEVICE_EVENTS_SUCCESS',
  FETCH_DEVICE_EVENTS_FAILURE: 'FETCH_DEVICE_EVENTS_FAILURE',
};

export default deviceEventActionTypes;