#
# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#

ARG REDIS_VERSION=alpine
FROM redis:${REDIS_VERSION}

ARG LOCAL_UID=65534
ARG LOCAL_GID=65534

ENV LOCAL_UID=$LOCAL_UID
ENV LOCAL_GID=$LOCAL_GID

USER $LOCAL_UID:$LOCAL_GID

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
