const deviceCategoryActionTypes = {
  // Index
  FETCH_DEVICE_CATEGORIES_START: 'FETCH_DEVICE_CATEGORIES_START',
  FETCH_DEVICE_CATEGORIES_SUCCESS: 'FETCH_DEVICE_CATEGORIES_SUCCESS',
  FETCH_DEVICE_CATEGORIES_FAILURE: 'FETCH_DEVICE_CATEGORIES_FAILURE',
  SET_FETCH_DEVICE_CATEGORIES_LAZY_PARAMS: 'SET_FETCH_DEVICE_CATEGORIES_LAZY_PARAMS',
  
  // Create
  CREATE_DEVICE_CATEGORY_START: 'CREATE_DEVICE_CATEGORY_START',
  CREATE_DEVICE_CATEGORY_SUCCESS: 'CREATE_DEVICE_CATEGORY_SUCCESS',
  CREATE_DEVICE_CATEGORY_FAILURE: 'CREATE_DEVICE_CATEGORY_FAILURE',

  // Read
  FETCH_DEVICE_CATEGORY_START: 'FETCH_DEVICE_CATEGORY_START',
  FETCH_DEVICE_CATEGORY_SUCCESS: 'FETCH_DEVICE_CATEGORY_SUCCESS',
  FETCH_DEVICE_CATEGORY_FAILURE: 'FETCH_DEVICE_CATEGORY_FAILURE',

  // Update
  UPDATE_DEVICE_CATEGORY_START: 'UPDATE_DEVICE_CATEGORY_START',
  UPDATE_DEVICE_CATEGORY_SUCCESS: 'UPDATE_DEVICE_CATEGORY_SUCCESS',
  UPDATE_DEVICE_CATEGORY_FAILURE: 'UPDATE_DEVICE_CATEGORY_FAILURE',

  // Delete Mass
  DELETE_DEVICE_CATEGORIES_START: 'DELETE_DEVICE_CATEGORIES_START',
  DELETE_DEVICE_CATEGORIES_SUCCESS: 'DELETE_DEVICE_CATEGORIES_SUCCESS',
  DELETE_DEVICE_CATEGORIES_FAILURE: 'DELETE_DEVICE_CATEGORIES_FAILURE',

  // Fetch dropdown options
  FETCH_DEVICE_CATEGORY_OPTIONS_START: 'FETCH_DEVICE_CATEGORY_OPTIONS_START',
  FETCH_DEVICE_CATEGORY_OPTIONS_SUCCESS: 'FETCH_DEVICE_CATEGORY_OPTIONS_SUCCESS',
  FETCH_DEVICE_CATEGORY_OPTIONS_FAILURE: 'FETCH_DEVICE_CATEGORY_OPTIONS_FAILURE',
};

export default deviceCategoryActionTypes;