const deviceCategoryActionTypes = {
  FETCH_DEVICE_CATEGORIES_START: 'FETCH_DEVICE_CATEGORIES_START',
  FETCH_DEVICE_CATEGORIES_SUCCESS: 'FETCH_DEVICE_CATEGORIES_SUCCESS',
  FETCH_DEVICE_CATEGORIES_FAILURE: 'FETCH_DEVICE_CATEGORIES_FAILURE',
};

export default deviceCategoryActionTypes;