const loginActionTypes = {
  // Read
  FETCH_USER_DETAILS_START: 'FETCH_USER_DETAILS_START',
  FETCH_USER_DETAILS_SUCCESS: 'FETCH_USER_DETAILS_SUCCESS',
  FETCH_USER_DETAILS_FAILURE: 'FETCH_USER_DETAILS_FAILURE',
};

export default loginActionTypes;