/*
 * Copyright (C) 2021 Intel Corporation
 * SPDX-License-Identifier: MIT
 */

const deviceEventHistoryActionTypes = {
  // Index
  FETCH_DEVICE_EVENT_HISTORIES_START: 'FETCH_DEVICE_EVENT_HISTORIES_START',
  FETCH_DEVICE_EVENT_HISTORIES_SUCCESS: 'FETCH_DEVICE_EVENT_HISTORIES_SUCCESS',
  FETCH_DEVICE_EVENT_HISTORIES_FAILURE: 'FETCH_DEVICE_EVENT_HISTORIES_FAILURE',
  SET_FETCH_DEVICE_EVENT_HISTORIES_LAZY_PARAMS: 'SET_FETCH_DEVICE_EVENT_HISTORIES_LAZY_PARAMS',
  RESET_FETCH_DEVICE_EVENT_HISTORIES_LAZY_PARAMS: 'RESET_FETCH_DEVICE_EVENT_HISTORIES_LAZY_PARAMS',
};

export default deviceEventHistoryActionTypes;