const deviceEventHistoryActionTypes = {
  FETCH_DEVICE_EVENT_HISTORIES_START: 'FETCH_DEVICE_EVENT_HISTORIES_START',
  FETCH_DEVICE_EVENT_HISTORIES_SUCCESS: 'FETCH_DEVICE_EVENT_HISTORIES_SUCCESS',
  FETCH_DEVICE_EVENT_HISTORIES_FAILURE: 'FETCH_DEVICE_EVENT_HISTORIES_FAILURE',
};

export default deviceEventHistoryActionTypes;