const jobActionTypes = {
  // Index
  FETCH_JOBS_START: 'FETCH_JOBS_START',
  FETCH_JOBS_SUCCESS: 'FETCH_JOBS_SUCCESS',
  FETCH_JOBS_FAILURE: 'FETCH_JOBS_FAILURE',
  SET_FETCH_JOBS_LAZY_PARAMS: 'SET_FETCH_JOBS_LAZY_PARAMS',
  RESET_FETCH_JOBS_LAZY_PARAMS: 'RESET_FETCH_JOBS_LAZY_PARAMS',

  // Create
  CREATE_JOB_START: 'CREATE_JOB_START',
  CREATE_JOB_SUCCESS: 'CREATE_JOB_SUCCESS',
  CREATE_JOB_FAILURE: 'CREATE_JOB_FAILURE',

  // Read
  FETCH_JOB_START: 'FETCH_JOB_START',
  FETCH_JOB_SUCCESS: 'FETCH_JOB_SUCCESS',
  FETCH_JOB_FAILURE: 'FETCH_JOB_FAILURE',

  // Update
  UPDATE_JOB_START: 'UPDATE_JOB_START',
  UPDATE_JOB_SUCCESS: 'UPDATE_JOB_SUCCESS',
  UPDATE_JOB_FAILURE: 'UPDATE_JOB_FAILURE',

  // Delete Mass
  DELETE_JOBS_START: 'DELETE_JOBS_START',
  DELETE_JOBS_SUCCESS: 'DELETE_JOBS_SUCCESS',
  DELETE_JOBS_FAILURE: 'DELETE_JOBS_FAILURE',
};

export default jobActionTypes;