/*
 * Copyright (C) 2021 Intel Corporation
 * SPDX-License-Identifier: MIT
 */

const dashboardActionTypes = {
  // Read statistics
  FETCH_DASHBOARD_STATISTICS_START: 'FETCH_DASHBOARD_STATISTICS_START',
  FETCH_DASHBOARD_STATISTICS_SUCCESS: 'FETCH_DASHBOARD_STATISTICS_SUCCESS',
  FETCH_DASHBOARD_STATISTICS_FAILURE: 'FETCH_DASHBOARD_STATISTICS_FAILURE',

  // Read CPU temperature chart
  FETCH_DASHBOARD_CPU_TEMPERATURES_START: 'FETCH_DASHBOARD_CPU_TEMPERATURES_START',
  FETCH_DASHBOARD_CPU_TEMPERATURES_SUCCESS: 'FETCH_DASHBOARD_CPU_TEMPERATURES_SUCCESS',
  FETCH_DASHBOARD_CPU_TEMPERATURES_FAILURE: 'FETCH_DASHBOARD_CPU_TEMPERATURES_FAILURE',

  // Read CPU usage chart
  FETCH_DASHBOARD_CPU_USAGES_START: 'FETCH_DASHBOARD_CPU_USAGES_START',
  FETCH_DASHBOARD_CPU_USAGES_SUCCESS: 'FETCH_DASHBOARD_CPU_USAGES_SUCCESS',
  FETCH_DASHBOARD_CPU_USAGES_FAILURE: 'FETCH_DASHBOARD_CPU_USAGES_FAILURE',

  // Read disk usage chart
  FETCH_DASHBOARD_DISK_USAGES_START: 'FETCH_DASHBOARD_DISK_USAGES_START',
  FETCH_DASHBOARD_DISK_USAGES_SUCCESS: 'FETCH_DASHBOARD_DISK_USAGES_SUCCESS',
  FETCH_DASHBOARD_DISK_USAGES_FAILURE: 'FETCH_DASHBOARD_DISK_USAGES_FAILURE',

  // Read available memory chart
  FETCH_DASHBOARD_AVAILABLE_MEMORIES_START: 'FETCH_DASHBOARD_AVAILABLE_MEMORIES_START',
  FETCH_DASHBOARD_AVAILABLE_MEMORIES_SUCCESS: 'FETCH_DASHBOARD_AVAILABLE_MEMORIES_SUCCESS',
  FETCH_DASHBOARD_AVAILABLE_MEMORIES_FAILURE: 'FETCH_DASHBOARD_AVAILABLE_MEMORIES_FAILURE',
};

export default dashboardActionTypes;