const fotaActionTypes = {
  // Submit FOTA
  SUBMIT_FOTA_START: 'SUBMIT_FOTA_START',
  SUBMIT_FOTA_SUCCESS: 'SUBMIT_FOTA_SUCCESS',
  SUBMIT_FOTA_FAILURE: 'SUBMIT_FOTA_FAILURE',
};

export default fotaActionTypes;