const shutdownActionTypes = {
  SUBMIT_SHUTDOWN_START: 'SUBMIT_SHUTDOWN_START',
  SUBMIT_SHUTDOWN_SUCCESS: 'SUBMIT_SHUTDOWN_SUCCESS',
  SUBMIT_SHUTDOWN_FAILURE: 'SUBMIT_SHUTDOWN_FAILURE',
};

export default shutdownActionTypes;