const deviceMetricActionTypes = {
  FETCH_TEMPERATURES_START: 'FETCH_TEMPERATURES_START',
  FETCH_TEMPERATURES_SUCCESS: 'FETCH_TEMPERATURES_SUCCESS',
  FETCH_TEMPERATURES_FAILURE: 'FETCH_TEMPERATURES_FAILURE',
  FETCH_CPU_USAGE_PERCENTAGES_START: 'FETCH_CPU_USAGE_PERCENTAGES_START',
  FETCH_CPU_USAGE_PERCENTAGES_SUCCESS: 'FETCH_CPU_USAGE_PERCENTAGES_SUCCESS',
  FETCH_CPU_USAGE_PERCENTAGES_FAILURE: 'FETCH_CPU_USAGE_PERCENTAGES_FAILURE',
  FETCH_DISK_USAGE_PERCENTAGES_START: 'FETCH_DISK_USAGE_PERCENTAGES_START',
  FETCH_DISK_USAGE_PERCENTAGES_SUCCESS: 'FETCH_DISK_USAGE_PERCENTAGES_SUCCESS',
  FETCH_DISK_USAGE_PERCENTAGES_FAILURE: 'FETCH_DISK_USAGE_PERCENTAGES_FAILURE',
  FETCH_AVAILABLE_MEMORIES_IN_BYTES_START: 'FETCH_AVAILABLE_MEMORIES_IN_BYTES_START',
  FETCH_AVAILABLE_MEMORIES_IN_BYTES_SUCCESS: 'FETCH_AVAILABLE_MEMORIES_IN_BYTES_SUCCESS',
  FETCH_AVAILABLE_MEMORIES_IN_BYTES_FAILURE: 'FETCH_AVAILABLE_MEMORIES_IN_BYTES_FAILURE',
};

export default deviceMetricActionTypes;